I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/conditions.rpy", line 1, in script
    define cond1 = false
  File "game/conditions.rpy", line 1, in script
    define cond1 = false
  File "game/conditions.rpy", line 1, in <module>
    define cond1 = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/conditions.rpy", line 1, in script
    define cond1 = false
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/conditions.rpy", line 1, in script
    define cond1 = false
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 2441, in execute
    self.set()
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/conditions.rpy", line 1, in <module>
    define cond1 = false
NameError: name 'false' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Chalice of Lendon 1.0
Sun Feb 19 17:59:26 2023
