I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    "This value should be 5 -> [gomaStats.amount]"
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "game/functional/statTracker.rpy", line 1, in execute
    screen track():
  File "game/functional/statTracker.rpy", line 1, in execute
    screen track():
  File "game/functional/statTracker.rpy", line 38, in execute
    $renpy.refresh_interaction()
  File "game/functional/statTracker.rpy", line 38, in <module>
    $renpy.refresh_interaction()
AttributeError: module 'renpy.exports' has no attribute 'refresh_interaction'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    "This value should be 5 -> [gomaStats.amount]"
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 891, in execute
    statement_name("say")
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 47, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/exports.py", line 1657, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 3810, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/screen.py", line 451, in visit_all
    callback(self)
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/core.py", line 3810, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/screen.py", line 462, in per_interact
    self.update()
  File "/Users/rdschultz/Desktop/renpy-8.0.3-sdk/renpy/display/screen.py", line 653, in update
    self.screen.function(**self.scope)
  File "game/functional/statTracker.rpy", line 1, in execute
    screen track():
  File "game/functional/statTracker.rpy", line 1, in execute
    screen track():
  File "game/functional/statTracker.rpy", line 38, in execute
    $renpy.refresh_interaction()
  File "game/functional/statTracker.rpy", line 38, in <module>
    $renpy.refresh_interaction()
AttributeError: module 'renpy.exports' has no attribute 'refresh_interaction'

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Chalice of Lendon 1.0
Thu Feb 23 12:16:18 2023
